[
  {"Title":"Star Wars: Episode IV - A New Hope","Year":"1977","Rated":"PG","Released":"25 May 1977","Runtime":"121 min","Genre":"Action, Adventure, Fantasy, Sci-Fi","Director":"George Lucas","Writer":"George Lucas","Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing","Plot":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.","Language":"English","Country":"USA","Awards":"Won 6 Oscars. Another 52 wins & 28 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"90/100"}],"Metascore":"90","imdbRating":"8.6","imdbVotes":"1,188,658","imdbID":"tt0076759","Type":"movie","DVD":"21 Sep 2004","BoxOffice":"N/A","Production":"20th Century Fox","Website":"N/A","Response":"True"},
  {"Title":"Parasite","Year":"2019","Rated":"R","Released":"08 Nov 2019","Runtime":"132 min","Genre":"Comedy, Drama, Thriller","Director":"Bong Joon Ho","Writer":"Bong Joon Ho (story), Bong Joon Ho (screenplay), Jin Won Han (screenplay)","Actors":"Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo, Woo-sik Choi","Plot":"Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.","Language":"Korean, English","Country":"South Korea","Awards":"Won 4 Oscars. Another 255 wins & 234 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"99%"},{"Source":"Metacritic","Value":"96/100"}],"Metascore":"96","imdbRating":"8.6","imdbVotes":"400,197","imdbID":"tt6751668","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Joker","Year":"2019","Rated":"R","Released":"04 Oct 2019","Runtime":"122 min","Genre":"Crime, Drama, Thriller","Director":"Todd Phillips","Writer":"Todd Phillips, Scott Silver, Bob Kane (based on characters created by), Bill Finger (based on characters created by), Jerry Robinson (based on characters created by)","Actors":"Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy","Plot":"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.","Language":"English","Country":"USA, Canada","Awards":"Won 2 Oscars. Another 93 wins & 198 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"68%"},{"Source":"Metacritic","Value":"59/100"}],"Metascore":"59","imdbRating":"8.5","imdbVotes":"748,514","imdbID":"tt7286456","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"1917","Year":"2019","Rated":"R","Released":"10 Jan 2020","Runtime":"119 min","Genre":"Drama, War","Director":"Sam Mendes","Writer":"Sam Mendes, Krysty Wilson-Cairns","Actors":"Dean-Charles Chapman, George MacKay, Daniel Mays, Colin Firth","Plot":"April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.","Language":"English, French, German","Country":"USA, UK, India, Spain, Canada","Awards":"Won 3 Oscars. Another 110 wins & 161 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"89%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"8.4","imdbVotes":"272,841","imdbID":"tt8579674","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"The Platform","Year":"2019","Rated":"TV-MA","Released":"20 Mar 2020","Runtime":"94 min","Genre":"Horror, Sci-Fi, Thriller","Director":"Galder Gaztelu-Urrutia","Writer":"David Desola (screenplay by), David Desola (story by), Pedro Rivero (screenplay by)","Actors":"Ivan Massagué, Zorion Eguileor, Antonia San Juan, Emilio Buale","Plot":"A vertical prison with one cell per level. Two people per cell. One only food platform and two minutes per day to feed from up to down. An endless nightmare trapped in The Hole.","Language":"Spanish","Country":"Spain","Awards":"9 wins & 14 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTMyYTIyM2MtNjQ2ZC00MWFkLThhYjQtMjhjMGZiMjgwYjM2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Metacritic","Value":"73/100"}],"Metascore":"73","imdbRating":"7.0","imdbVotes":"97,595","imdbID":"tt8228288","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Breaking Bad","Year":"2008–2013","Rated":"TV-MA","Released":"20 Jan 2008","Runtime":"49 min","Genre":"Crime, Drama, Thriller","Director":"N/A","Writer":"Vince Gilligan","Actors":"Bryan Cranston, Anna Gunn, Aaron Paul, Betsy Brandt","Plot":"A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.","Language":"English, Spanish","Country":"USA","Awards":"Won 2 Golden Globes. Another 151 wins & 234 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.5/10"},{"Source":"Rotten Tomatoes","Value":"96%"}],"Metascore":"N/A","imdbRating":"9.5","imdbVotes":"1,346,693","imdbID":"tt0903747","Type":"series","totalSeasons":"5","Response":"True"},
  {"Title":"Game of Thrones","Year":"2011–","Rated":"TV-MA","Released":"17 Apr 2011","Runtime":"57 min","Genre":"Action, Adventure, Drama, Fantasy, Romance","Director":"N/A","Writer":"David Benioff, D.B. Weiss","Actors":"Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington","Plot":"Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.","Language":"English","Country":"USA, UK","Awards":"Won 1 Golden Globe. Another 273 wins & 454 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjA5NzA5NjMwNl5BMl5BanBnXkFtZTgwNjg2OTk2NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.5/10"}],"Metascore":"N/A","imdbRating":"9.5","imdbVotes":"1,429,496","imdbID":"tt0944947","Type":"series","totalSeasons":"8","Response":"True"},
  {"Title":"Interstellar","Year":"2014","Rated":"PG-13","Released":"07 Nov 2014","Runtime":"169 min","Genre":"Adventure, Drama, Sci-Fi, Thriller","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan","Actors":"Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow","Plot":"A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.","Language":"English","Country":"USA, UK, Canada","Awards":"Won 1 Oscar. Another 43 wins & 147 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"72%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.6","imdbVotes":"1,395,990","imdbID":"tt0816692","Type":"movie","DVD":"31 Mar 2015","BoxOffice":"$158,737,441","Production":"Paramount Pictures","Website":"N/A","Response":"True"},
  {"Title":"Inception","Year":"2010","Rated":"PG-13","Released":"16 Jul 2010","Runtime":"148 min","Genre":"Action, Adventure, Sci-Fi, Thriller","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy","Plot":"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.","Language":"English, Japanese, French","Country":"USA, UK","Awards":"Won 4 Oscars. Another 152 wins & 217 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.8","imdbVotes":"1,953,512","imdbID":"tt1375666","Type":"movie","DVD":"07 Dec 2010","BoxOffice":"$292,568,851","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
  {"Title":"Once Upon a Time... in Hollywood","Year":"2019","Rated":"R","Released":"26 Jul 2019","Runtime":"161 min","Genre":"Comedy, Drama","Director":"Quentin Tarantino","Writer":"Quentin Tarantino","Actors":"Leonardo DiCaprio, Brad Pitt, Margot Robbie, Emile Hirsch","Plot":"A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.","Language":"English, German, Italian, Spanish","Country":"USA, UK, China","Awards":"Won 2 Oscars. Another 125 wins & 341 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"85%"},{"Source":"Metacritic","Value":"83/100"}],"Metascore":"83","imdbRating":"7.7","imdbVotes":"434,088","imdbID":"tt7131622","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Upload","Year":"2007","Rated":"X","Released":"N/A","Runtime":"285 min","Genre":"Adult","Director":"Bryn Pryor","Writer":"Alvin Edwards (screenplay), Bryn Pryor (screenplay)","Actors":"Hillary Scott, Eva Angelina, Derrick Pierce, Trina Michaels","Plot":"A caption states that it's the near future. In an office, an interrogator (never named) asks DSA (Digital Security Agency, a part of the futuristic Department of Homeland Security) agent ...","Language":"English","Country":"USA","Awards":"12 wins & 13 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMzdiODVkOGMtMTQ2MS00NWRiLWFhZmItZTY0NmNjZDI3OWY1XkEyXkFqcGdeQXVyMTgwOTE5NDk@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"}],"Metascore":"N/A","imdbRating":"7.4","imdbVotes":"82","imdbID":"tt1160623","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Forrest Gump","Year":"1994","Rated":"PG-13","Released":"06 Jul 1994","Runtime":"142 min","Genre":"Drama, Romance","Director":"Robert Zemeckis","Writer":"Winston Groom (novel), Eric Roth (screenplay)","Actors":"Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys","Plot":"The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.","Language":"English","Country":"USA","Awards":"Won 6 Oscars. Another 44 wins & 74 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"70%"},{"Source":"Metacritic","Value":"82/100"}],"Metascore":"82","imdbRating":"8.8","imdbVotes":"1,722,338","imdbID":"tt0109830","Type":"movie","DVD":"28 Aug 2001","BoxOffice":"$330,000,000","Production":"Paramount Pictures","Website":"N/A","Response":"True"},
  {"Title":"The Dark Knight","Year":"2008","Rated":"PG-13","Released":"18 Jul 2008","Runtime":"152 min","Genre":"Action, Crime, Drama, Thriller","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)","Actors":"Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine","Plot":"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.","Language":"English, Mandarin","Country":"USA, UK","Awards":"Won 2 Oscars. Another 153 wins & 159 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.0/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"84/100"}],"Metascore":"84","imdbRating":"9.0","imdbVotes":"2,200,152","imdbID":"tt0468569","Type":"movie","DVD":"09 Dec 2008","BoxOffice":"$533,316,061","Production":"Warner Bros. Pictures/Legendary","Website":"N/A","Response":"True"},
  {"Title":"Into the Night","Year":"1985","Rated":"R","Released":"22 Feb 1985","Runtime":"115 min","Genre":"Comedy, Crime, Drama, Romance, Thriller","Director":"John Landis","Writer":"Ron Koslow","Actors":"Jeff Goldblum, Stacey Pickren, Carmen Argenziano, Andrew Marton","Plot":"After discovering that his wife is cheating on him, an insomniac aerospace engineer accidentally meets, and tries to help a beautiful model on the run from some extremely dangerous people.","Language":"English, Persian, French, Spanish","Country":"USA","Awards":"1 win.","Poster":"https://m.media-amazon.com/images/M/MV5BODliOGY1OWItNTkzNy00YzJiLWEzMmMtMWM4NWZlZmE4MWE5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.4/10"},{"Source":"Rotten Tomatoes","Value":"38%"},{"Source":"Metacritic","Value":"41/100"}],"Metascore":"41","imdbRating":"6.4","imdbVotes":"10,486","imdbID":"tt0089346","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Fight Club","Year":"1999","Rated":"R","Released":"15 Oct 1999","Runtime":"139 min","Genre":"Drama","Director":"David Fincher","Writer":"Chuck Palahniuk (novel), Jim Uhls (screenplay)","Actors":"Edward Norton, Brad Pitt, Meat Loaf, Zach Grenier","Plot":"An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.","Language":"English","Country":"USA, Germany","Awards":"Nominated for 1 Oscar. Another 10 wins & 37 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"78%"},{"Source":"Metacritic","Value":"66/100"}],"Metascore":"66","imdbRating":"8.8","imdbVotes":"1,768,254","imdbID":"tt0137523","Type":"movie","DVD":"06 Jun 2000","BoxOffice":"N/A","Production":"20th Century Fox","Website":"N/A","Response":"True"},
  {"Title":"Pulp Fiction","Year":"1994","Rated":"R","Released":"14 Oct 1994","Runtime":"154 min","Genre":"Crime, Drama","Director":"Quentin Tarantino","Writer":"Quentin Tarantino (stories), Roger Avary (stories), Quentin Tarantino","Actors":"Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta","Plot":"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.","Language":"English, Spanish, French","Country":"USA","Awards":"Won 1 Oscar. Another 68 wins & 74 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.9/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"94/100"}],"Metascore":"94","imdbRating":"8.9","imdbVotes":"1,744,145","imdbID":"tt0110912","Type":"movie","DVD":"19 May 1998","BoxOffice":"N/A","Production":"Miramax Films","Website":"N/A","Response":"True"},
  {"Title":"Never Have I Ever","Year":"2020–","Rated":"TV-14","Released":"27 Apr 2020","Runtime":"N/A","Genre":"Comedy","Director":"N/A","Writer":"Lang Fisher, Mindy Kaling","Actors":"Maitreyi Ramakrishnan, Poorna Jagannathan, Lee Rodriguez, Richa Moorjani","Plot":"The complicated life of a modern-day first generation Indian American teenage girl, inspired by Kaling's own childhood.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BNGIyMzBkNjMtZWViYy00YTMxLThhN2UtMjRjMzgxOGFmOTc5XkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"}],"Metascore":"N/A","imdbRating":"7.9","imdbVotes":"657","imdbID":"tt10062292","Type":"series","totalSeasons":"1","Response":"True"},
  {"Title":"Django Unchained","Year":"2012","Rated":"R","Released":"25 Dec 2012","Runtime":"165 min","Genre":"Drama, Western","Director":"Quentin Tarantino","Writer":"Quentin Tarantino","Actors":"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington","Plot":"With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.","Language":"English, German, French, Italian","Country":"USA","Awards":"Won 2 Oscars. Another 57 wins & 155 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"81/100"}],"Metascore":"81","imdbRating":"8.4","imdbVotes":"1,282,957","imdbID":"tt1853728","Type":"movie","DVD":"16 Apr 2013","BoxOffice":"$162,804,648","Production":"The Weinstein Co.","Website":"N/A","Response":"True"},
  



















  {"Title":"The Matrix","Year":"1999","Rated":"R","Released":"31 Mar 1999","Runtime":"136 min","Genre":"Action, Sci-Fi","Director":"Lana Wachowski, Lilly Wachowski","Writer":"Lilly Wachowski, Lana Wachowski","Actors":"Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving","Plot":"A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.","Language":"English","Country":"USA","Awards":"Won 4 Oscars. Another 37 wins & 50 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.7/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"73/100"}],"Metascore":"73","imdbRating":"8.7","imdbVotes":"1,597,196","imdbID":"tt0133093","Type":"movie","DVD":"21 Sep 1999","BoxOffice":"N/A","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
  {"Title":"The Usual Suspects","Year":"1995","Rated":"R","Released":"16 Aug 1995","Runtime":"106 min","Genre":"Crime, Mystery, Thriller","Director":"Bryan Singer","Writer":"Christopher McQuarrie","Actors":"Stephen Baldwin, Gabriel Byrne, Benicio Del Toro, Kevin Pollak","Plot":"A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.","Language":"English, Hungarian, Spanish, French","Country":"USA, Germany","Awards":"Won 2 Oscars. Another 35 wins & 16 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"89%"},{"Source":"Metacritic","Value":"77/100"}],"Metascore":"77","imdbRating":"8.5","imdbVotes":"951,109","imdbID":"tt0114814","Type":"movie","DVD":"09 Dec 1999","BoxOffice":"N/A","Production":"Gramercy Pictures","Website":"N/A","Response":"True"},
  {"Title":"The Wolf of Wall Street","Year":"2013","Rated":"R","Released":"25 Dec 2013","Runtime":"180 min","Genre":"Biography, Crime, Drama","Director":"Martin Scorsese","Writer":"Terence Winter (screenplay), Jordan Belfort (book)","Actors":"Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey","Plot":"Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.","Language":"English, French","Country":"USA","Awards":"Nominated for 5 Oscars. Another 38 wins & 172 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"},{"Source":"Rotten Tomatoes","Value":"79%"},{"Source":"Metacritic","Value":"75/100"}],"Metascore":"75","imdbRating":"8.2","imdbVotes":"1,107,316","imdbID":"tt0993846","Type":"movie","DVD":"25 Mar 2014","BoxOffice":"$91,330,760","Production":"Paramount Studios","Website":"N/A","Response":"True"},
  {"Title":"The Shawshank Redemption","Year":"1994","Rated":"R","Released":"14 Oct 1994","Runtime":"142 min","Genre":"Drama","Director":"Frank Darabont","Writer":"Stephen King (short story \"Rita Hayworth and Shawshank Redemption\"), Frank Darabont (screenplay)","Actors":"Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler","Plot":"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.","Language":"English","Country":"USA","Awards":"Nominated for 7 Oscars. Another 21 wins & 35 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.3/10"},{"Source":"Rotten Tomatoes","Value":"90%"},{"Source":"Metacritic","Value":"80/100"}],"Metascore":"80","imdbRating":"9.3","imdbVotes":"2,217,195","imdbID":"tt0111161","Type":"movie","DVD":"27 Jan 1998","BoxOffice":"N/A","Production":"Columbia Pictures","Website":"N/A","Response":"True"},
  {"Title":"Memento","Year":"2000","Rated":"R","Released":"25 May 2001","Runtime":"113 min","Genre":"Mystery, Thriller","Director":"Christopher Nolan","Writer":"Christopher Nolan (screenplay), Jonathan Nolan (short story \"Memento Mori\")","Actors":"Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junior","Plot":"A man with short-term memory loss attempts to track down his wife's murderer.","Language":"English","Country":"USA","Awards":"Nominated for 2 Oscars. Another 57 wins & 56 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"93%"},{"Source":"Metacritic","Value":"80/100"}],"Metascore":"80","imdbRating":"8.4","imdbVotes":"1,080,620","imdbID":"tt0209144","Type":"movie","DVD":"04 Sep 2001","BoxOffice":"$23,844,220","Production":"Newmarket Films","Website":"N/A","Response":"True"},
  {"Title":"The Prestige","Year":"2006","Rated":"PG-13","Released":"20 Oct 2006","Runtime":"130 min","Genre":"Drama, Mystery, Sci-Fi, Thriller","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Priest (novel)","Actors":"Hugh Jackman, Christian Bale, Michael Caine, Piper Perabo","Plot":"After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.","Language":"English","Country":"USA, UK","Awards":"Nominated for 2 Oscars. Another 6 wins & 38 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"75%"},{"Source":"Metacritic","Value":"66/100"}],"Metascore":"66","imdbRating":"8.5","imdbVotes":"1,124,164","imdbID":"tt0482571","Type":"movie","DVD":"20 Feb 2007","BoxOffice":"$53,100,000","Production":"Buena Vista Pictures","Website":"N/A","Response":"True"},
  {"Title":"Léon: The Professional","Year":"1994","Rated":"R","Released":"18 Nov 1994","Runtime":"110 min","Genre":"Action, Crime, Drama, Thriller","Director":"Luc Besson","Writer":"Luc Besson","Actors":"Jean Reno, Gary Oldman, Natalie Portman, Danny Aiello","Plot":"Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.","Language":"English, Italian, French","Country":"France, USA","Awards":"6 wins & 14 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BZDAwYTlhMDEtNTg0OS00NDY2LWJjOWItNWY3YTZkM2UxYzUzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"73%"},{"Source":"Metacritic","Value":"64/100"}],"Metascore":"64","imdbRating":"8.5","imdbVotes":"986,202","imdbID":"tt0110413","Type":"movie","DVD":"15 Aug 2000","BoxOffice":"N/A","Production":"Columbia Pictures","Website":"N/A","Response":"True"},
  {"Title":"Blood Diamond","Year":"2006","Rated":"R","Released":"08 Dec 2006","Runtime":"143 min","Genre":"Adventure, Drama, Thriller","Director":"Edward Zwick","Writer":"Charles Leavitt (screenplay), Charles Leavitt (story), C. Gaby Mitchell (story)","Actors":"Leonardo DiCaprio, Djimon Hounsou, Jennifer Connelly, Kagiso Kuypers","Plot":"A fisherman, a smuggler, and a syndicate of businessmen match wits over the possession of a priceless diamond.","Language":"English, Mende, Afrikaans","Country":"USA, Germany","Awards":"Nominated for 5 Oscars. Another 8 wins & 27 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BZDMxOGZhNWYtMzRlYy00Mzk5LWJjMjEtNmQ4NDU4M2QxM2UzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"63%"},{"Source":"Metacritic","Value":"64/100"}],"Metascore":"64","imdbRating":"8.0","imdbVotes":"481,941","imdbID":"tt0450259","Type":"movie","DVD":"20 Mar 2007","BoxOffice":"$57,300,000","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
  {"Title":"The Departed","Year":"2006","Rated":"R","Released":"06 Oct 2006","Runtime":"151 min","Genre":"Crime, Drama, Thriller","Director":"Martin Scorsese","Writer":"William Monahan (screenplay), Alan Mak, Felix Chong","Actors":"Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg","Plot":"An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.","Language":"English, Cantonese","Country":"USA","Awards":"Won 4 Oscars. Another 94 wins & 139 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"91%"},{"Source":"Metacritic","Value":"85/100"}],"Metascore":"85","imdbRating":"8.5","imdbVotes":"1,136,749","imdbID":"tt0407887","Type":"movie","DVD":"13 Feb 2007","BoxOffice":"$132,300,000","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
  {"Title":"Castaway","Year":"1986","Rated":"R","Released":"11 Sep 1987","Runtime":"117 min","Genre":"Adventure, Drama","Director":"Nicolas Roeg","Writer":"Lucy Irvine (book), Allan Scott","Actors":"Oliver Reed, Amanda Donohoe, Georgina Hale, Frances Barber","Plot":"Middle-aged Gerald Kingsland advertises in a London paper for a female companion to spend a year with him on a desert island.","Language":"English","Country":"UK","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BMTY5MzI4Mzc4OV5BMl5BanBnXkFtZTgwNTM5MzkwMzE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.8/10"},{"Source":"Rotten Tomatoes","Value":"100%"}],"Metascore":"N/A","imdbRating":"5.8","imdbVotes":"2,954","imdbID":"tt0092732","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Zombieland","Year":"2009","Rated":"R","Released":"02 Oct 2009","Runtime":"88 min","Genre":"Adventure, Comedy, Horror, Sci-Fi","Director":"Ruben Fleischer","Writer":"Rhett Reese, Paul Wernick","Actors":"Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin","Plot":"A shy student trying to reach his family in Ohio, a gun-toting tough guy trying to find the last Twinkie, and a pair of sisters trying to get to an amusement park join forces to travel across a zombie-filled America.","Language":"English","Country":"USA","Awards":"10 wins & 28 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTU5MDg0NTQ1N15BMl5BanBnXkFtZTcwMjA4Mjg3Mg@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.6/10"},{"Source":"Rotten Tomatoes","Value":"90%"},{"Source":"Metacritic","Value":"73/100"}],"Metascore":"73","imdbRating":"7.6","imdbVotes":"501,427","imdbID":"tt1156398","Type":"movie","DVD":"02 Feb 2010","BoxOffice":"$75,590,286","Production":"Sony/Columbia Pictures","Website":"N/A","Response":"True"}
















]