[
  {"Title":"Star Wars: Episode IV - A New Hope","Year":"1977","Rated":"PG","Released":"25 May 1977","Runtime":"121 min","Genre":"Action, Adventure, Fantasy, Sci-Fi","Director":"George Lucas","Writer":"George Lucas","Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing","Plot":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.","Language":"English","Country":"USA","Awards":"Won 6 Oscars. Another 52 wins & 28 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"90/100"}],"Metascore":"90","imdbRating":"8.6","imdbVotes":"1,188,658","imdbID":"tt0076759","Type":"movie","DVD":"21 Sep 2004","BoxOffice":"N/A","Production":"20th Century Fox","Website":"N/A","Response":"True"},
  {"Title":"Parasite","Year":"2019","Rated":"R","Released":"08 Nov 2019","Runtime":"132 min","Genre":"Comedy, Drama, Thriller","Director":"Bong Joon Ho","Writer":"Bong Joon Ho (story), Bong Joon Ho (screenplay), Jin Won Han (screenplay)","Actors":"Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo, Woo-sik Choi","Plot":"Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.","Language":"Korean, English","Country":"South Korea","Awards":"Won 4 Oscars. Another 255 wins & 234 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"99%"},{"Source":"Metacritic","Value":"96/100"}],"Metascore":"96","imdbRating":"8.6","imdbVotes":"400,197","imdbID":"tt6751668","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Joker","Year":"2019","Rated":"R","Released":"04 Oct 2019","Runtime":"122 min","Genre":"Crime, Drama, Thriller","Director":"Todd Phillips","Writer":"Todd Phillips, Scott Silver, Bob Kane (based on characters created by), Bill Finger (based on characters created by), Jerry Robinson (based on characters created by)","Actors":"Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy","Plot":"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.","Language":"English","Country":"USA, Canada","Awards":"Won 2 Oscars. Another 93 wins & 198 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"68%"},{"Source":"Metacritic","Value":"59/100"}],"Metascore":"59","imdbRating":"8.5","imdbVotes":"748,514","imdbID":"tt7286456","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"1917","Year":"2019","Rated":"R","Released":"10 Jan 2020","Runtime":"119 min","Genre":"Drama, War","Director":"Sam Mendes","Writer":"Sam Mendes, Krysty Wilson-Cairns","Actors":"Dean-Charles Chapman, George MacKay, Daniel Mays, Colin Firth","Plot":"April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.","Language":"English, French, German","Country":"USA, UK, India, Spain, Canada","Awards":"Won 3 Oscars. Another 110 wins & 161 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"89%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"8.4","imdbVotes":"272,841","imdbID":"tt8579674","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"The Platform","Year":"2019","Rated":"TV-MA","Released":"20 Mar 2020","Runtime":"94 min","Genre":"Horror, Sci-Fi, Thriller","Director":"Galder Gaztelu-Urrutia","Writer":"David Desola (screenplay by), David Desola (story by), Pedro Rivero (screenplay by)","Actors":"Ivan Massagué, Zorion Eguileor, Antonia San Juan, Emilio Buale","Plot":"A vertical prison with one cell per level. Two people per cell. One only food platform and two minutes per day to feed from up to down. An endless nightmare trapped in The Hole.","Language":"Spanish","Country":"Spain","Awards":"9 wins & 14 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTMyYTIyM2MtNjQ2ZC00MWFkLThhYjQtMjhjMGZiMjgwYjM2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Metacritic","Value":"73/100"}],"Metascore":"73","imdbRating":"7.0","imdbVotes":"97,595","imdbID":"tt8228288","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Breaking Bad","Year":"2008–2013","Rated":"TV-MA","Released":"20 Jan 2008","Runtime":"49 min","Genre":"Crime, Drama, Thriller","Director":"N/A","Writer":"Vince Gilligan","Actors":"Bryan Cranston, Anna Gunn, Aaron Paul, Betsy Brandt","Plot":"A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.","Language":"English, Spanish","Country":"USA","Awards":"Won 2 Golden Globes. Another 151 wins & 234 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.5/10"},{"Source":"Rotten Tomatoes","Value":"96%"}],"Metascore":"N/A","imdbRating":"9.5","imdbVotes":"1,346,693","imdbID":"tt0903747","Type":"series","totalSeasons":"5","Response":"True"},
  {"Title":"Game of Thrones","Year":"2011–","Rated":"TV-MA","Released":"17 Apr 2011","Runtime":"57 min","Genre":"Action, Adventure, Drama, Fantasy, Romance","Director":"N/A","Writer":"David Benioff, D.B. Weiss","Actors":"Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington","Plot":"Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.","Language":"English","Country":"USA, UK","Awards":"Won 1 Golden Globe. Another 273 wins & 454 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjA5NzA5NjMwNl5BMl5BanBnXkFtZTgwNjg2OTk2NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.5/10"}],"Metascore":"N/A","imdbRating":"9.5","imdbVotes":"1,429,496","imdbID":"tt0944947","Type":"series","totalSeasons":"8","Response":"True"},
  {"Title":"Interstellar","Year":"2014","Rated":"PG-13","Released":"07 Nov 2014","Runtime":"169 min","Genre":"Adventure, Drama, Sci-Fi, Thriller","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan","Actors":"Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow","Plot":"A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.","Language":"English","Country":"USA, UK, Canada","Awards":"Won 1 Oscar. Another 43 wins & 147 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"72%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.6","imdbVotes":"1,395,990","imdbID":"tt0816692","Type":"movie","DVD":"31 Mar 2015","BoxOffice":"$158,737,441","Production":"Paramount Pictures","Website":"N/A","Response":"True"},
  {"Title":"Inception","Year":"2010","Rated":"PG-13","Released":"16 Jul 2010","Runtime":"148 min","Genre":"Action, Adventure, Sci-Fi, Thriller","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy","Plot":"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.","Language":"English, Japanese, French","Country":"USA, UK","Awards":"Won 4 Oscars. Another 152 wins & 217 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.8","imdbVotes":"1,953,512","imdbID":"tt1375666","Type":"movie","DVD":"07 Dec 2010","BoxOffice":"$292,568,851","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
  {"Title":"Once Upon a Time... in Hollywood","Year":"2019","Rated":"R","Released":"26 Jul 2019","Runtime":"161 min","Genre":"Comedy, Drama","Director":"Quentin Tarantino","Writer":"Quentin Tarantino","Actors":"Leonardo DiCaprio, Brad Pitt, Margot Robbie, Emile Hirsch","Plot":"A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.","Language":"English, German, Italian, Spanish","Country":"USA, UK, China","Awards":"Won 2 Oscars. Another 125 wins & 341 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"85%"},{"Source":"Metacritic","Value":"83/100"}],"Metascore":"83","imdbRating":"7.7","imdbVotes":"434,088","imdbID":"tt7131622","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Upload","Year":"2007","Rated":"X","Released":"N/A","Runtime":"285 min","Genre":"Adult","Director":"Bryn Pryor","Writer":"Alvin Edwards (screenplay), Bryn Pryor (screenplay)","Actors":"Hillary Scott, Eva Angelina, Derrick Pierce, Trina Michaels","Plot":"A caption states that it's the near future. In an office, an interrogator (never named) asks DSA (Digital Security Agency, a part of the futuristic Department of Homeland Security) agent ...","Language":"English","Country":"USA","Awards":"12 wins & 13 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMzdiODVkOGMtMTQ2MS00NWRiLWFhZmItZTY0NmNjZDI3OWY1XkEyXkFqcGdeQXVyMTgwOTE5NDk@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"}],"Metascore":"N/A","imdbRating":"7.4","imdbVotes":"82","imdbID":"tt1160623","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Forrest Gump","Year":"1994","Rated":"PG-13","Released":"06 Jul 1994","Runtime":"142 min","Genre":"Drama, Romance","Director":"Robert Zemeckis","Writer":"Winston Groom (novel), Eric Roth (screenplay)","Actors":"Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys","Plot":"The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.","Language":"English","Country":"USA","Awards":"Won 6 Oscars. Another 44 wins & 74 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"70%"},{"Source":"Metacritic","Value":"82/100"}],"Metascore":"82","imdbRating":"8.8","imdbVotes":"1,722,338","imdbID":"tt0109830","Type":"movie","DVD":"28 Aug 2001","BoxOffice":"$330,000,000","Production":"Paramount Pictures","Website":"N/A","Response":"True"},
  {"Title":"The Dark Knight","Year":"2008","Rated":"PG-13","Released":"18 Jul 2008","Runtime":"152 min","Genre":"Action, Crime, Drama, Thriller","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)","Actors":"Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine","Plot":"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.","Language":"English, Mandarin","Country":"USA, UK","Awards":"Won 2 Oscars. Another 153 wins & 159 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.0/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"84/100"}],"Metascore":"84","imdbRating":"9.0","imdbVotes":"2,200,152","imdbID":"tt0468569","Type":"movie","DVD":"09 Dec 2008","BoxOffice":"$533,316,061","Production":"Warner Bros. Pictures/Legendary","Website":"N/A","Response":"True"},
  {"Title":"Into the Night","Year":"1985","Rated":"R","Released":"22 Feb 1985","Runtime":"115 min","Genre":"Comedy, Crime, Drama, Romance, Thriller","Director":"John Landis","Writer":"Ron Koslow","Actors":"Jeff Goldblum, Stacey Pickren, Carmen Argenziano, Andrew Marton","Plot":"After discovering that his wife is cheating on him, an insomniac aerospace engineer accidentally meets, and tries to help a beautiful model on the run from some extremely dangerous people.","Language":"English, Persian, French, Spanish","Country":"USA","Awards":"1 win.","Poster":"https://m.media-amazon.com/images/M/MV5BODliOGY1OWItNTkzNy00YzJiLWEzMmMtMWM4NWZlZmE4MWE5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.4/10"},{"Source":"Rotten Tomatoes","Value":"38%"},{"Source":"Metacritic","Value":"41/100"}],"Metascore":"41","imdbRating":"6.4","imdbVotes":"10,486","imdbID":"tt0089346","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Fight Club","Year":"1999","Rated":"R","Released":"15 Oct 1999","Runtime":"139 min","Genre":"Drama","Director":"David Fincher","Writer":"Chuck Palahniuk (novel), Jim Uhls (screenplay)","Actors":"Edward Norton, Brad Pitt, Meat Loaf, Zach Grenier","Plot":"An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.","Language":"English","Country":"USA, Germany","Awards":"Nominated for 1 Oscar. Another 10 wins & 37 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"78%"},{"Source":"Metacritic","Value":"66/100"}],"Metascore":"66","imdbRating":"8.8","imdbVotes":"1,768,254","imdbID":"tt0137523","Type":"movie","DVD":"06 Jun 2000","BoxOffice":"N/A","Production":"20th Century Fox","Website":"N/A","Response":"True"},
  {"Title":"Pulp Fiction","Year":"1994","Rated":"R","Released":"14 Oct 1994","Runtime":"154 min","Genre":"Crime, Drama","Director":"Quentin Tarantino","Writer":"Quentin Tarantino (stories), Roger Avary (stories), Quentin Tarantino","Actors":"Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta","Plot":"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.","Language":"English, Spanish, French","Country":"USA","Awards":"Won 1 Oscar. Another 68 wins & 74 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.9/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"94/100"}],"Metascore":"94","imdbRating":"8.9","imdbVotes":"1,744,145","imdbID":"tt0110912","Type":"movie","DVD":"19 May 1998","BoxOffice":"N/A","Production":"Miramax Films","Website":"N/A","Response":"True"},
  {"Title":"Never Have I Ever","Year":"2020–","Rated":"TV-14","Released":"27 Apr 2020","Runtime":"N/A","Genre":"Comedy","Director":"N/A","Writer":"Lang Fisher, Mindy Kaling","Actors":"Maitreyi Ramakrishnan, Poorna Jagannathan, Lee Rodriguez, Richa Moorjani","Plot":"The complicated life of a modern-day first generation Indian American teenage girl, inspired by Kaling's own childhood.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BNGIyMzBkNjMtZWViYy00YTMxLThhN2UtMjRjMzgxOGFmOTc5XkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"}],"Metascore":"N/A","imdbRating":"7.9","imdbVotes":"657","imdbID":"tt10062292","Type":"series","totalSeasons":"1","Response":"True"},
  {"Title":"Django Unchained","Year":"2012","Rated":"R","Released":"25 Dec 2012","Runtime":"165 min","Genre":"Drama, Western","Director":"Quentin Tarantino","Writer":"Quentin Tarantino","Actors":"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington","Plot":"With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.","Language":"English, German, French, Italian","Country":"USA","Awards":"Won 2 Oscars. Another 57 wins & 155 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"81/100"}],"Metascore":"81","imdbRating":"8.4","imdbVotes":"1,282,957","imdbID":"tt1853728","Type":"movie","DVD":"16 Apr 2013","BoxOffice":"$162,804,648","Production":"The Weinstein Co.","Website":"N/A","Response":"True"},
  











  {"Title":"Joker","Year":"2019","Rated":"R","Released":"04 Oct 2019","Runtime":"122 min","Genre":"Crime, Drama, Thriller","Director":"Todd Phillips","Writer":"Todd Phillips, Scott Silver, Bob Kane (based on characters created by), Bill Finger (based on characters created by), Jerry Robinson (based on characters created by)","Actors":"Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy","Plot":"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.","Language":"English","Country":"USA, Canada","Awards":"Won 2 Oscars. Another 93 wins & 198 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"68%"},{"Source":"Metacritic","Value":"59/100"}],"Metascore":"59","imdbRating":"8.5","imdbVotes":"748,514","imdbID":"tt7286456","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Godfather","Year":"1991","Rated":"Not Rated","Released":"15 Nov 1991","Runtime":"150 min","Genre":"Comedy, Drama, Romance","Director":"Lal, Siddique","Writer":"Lal (screenplay, story & dialogue), Siddique","Actors":"N.N. Pillai, Mukesh, Kanaka, Philomina","Plot":"Two youngsters from rival clans fall in love.","Language":"Malayalam","Country":"India","Awards":"2 wins.","Poster":"https://m.media-amazon.com/images/M/MV5BZTkyYzc5MGEtYTBiYS00ZmYyLThlZWUtOWY3ZWE4ZDhlN2MzXkEyXkFqcGdeQXVyMjM0ODk5MDU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"}],"Metascore":"N/A","imdbRating":"8.6","imdbVotes":"2,644","imdbID":"tt0353496","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"The Breakfast Club","Year":"1985","Rated":"R","Released":"15 Feb 1985","Runtime":"97 min","Genre":"Comedy, Drama","Director":"John Hughes","Writer":"John Hughes","Actors":"Emilio Estevez, Paul Gleason, Anthony Michael Hall, John Kapelos","Plot":"Five high school students meet in Saturday detention and discover how they have a lot more in common than they thought.","Language":"English","Country":"USA","Awards":"3 wins.","Poster":"https://m.media-amazon.com/images/M/MV5BOTM5N2ZmZTMtNjlmOS00YzlkLTk3YjEtNTU1ZmQ5OTdhODZhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"},{"Source":"Rotten Tomatoes","Value":"89%"},{"Source":"Metacritic","Value":"62/100"}],"Metascore":"62","imdbRating":"7.9","imdbVotes":"337,142","imdbID":"tt0088847","Type":"movie","DVD":"02 Sep 2003","BoxOffice":"N/A","Production":"Universal Pictures","Website":"N/A","Response":"True"},
  {"Title":"Django Unchained","Year":"2012","Rated":"R","Released":"25 Dec 2012","Runtime":"165 min","Genre":"Drama, Western","Director":"Quentin Tarantino","Writer":"Quentin Tarantino","Actors":"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington","Plot":"With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.","Language":"English, German, French, Italian","Country":"USA","Awards":"Won 2 Oscars. Another 57 wins & 155 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"81/100"}],"Metascore":"81","imdbRating":"8.4","imdbVotes":"1,282,957","imdbID":"tt1853728","Type":"movie","DVD":"16 Apr 2013","BoxOffice":"$162,804,648","Production":"The Weinstein Co.","Website":"N/A","Response":"True"},
  {"Title":"Pineapple Express","Year":"2008","Rated":"R","Released":"06 Aug 2008","Runtime":"111 min","Genre":"Action, Comedy, Crime","Director":"David Gordon Green","Writer":"Seth Rogen (screenplay), Evan Goldberg (screenplay), Judd Apatow (story), Seth Rogen (story), Evan Goldberg (story)","Actors":"Seth Rogen, James Franco, Danny McBride, Kevin Corrigan","Plot":"A process server and his marijuana dealer wind up on the run from hitmen and a corrupt police officer after he witnesses his dealer's boss murder a competitor while trying to serve papers on him.","Language":"English, Cantonese, Korean","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 2 wins & 14 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTY1MTE4NzAwM15BMl5BanBnXkFtZTcwNzg3Mjg2MQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Metacritic","Value":"64/100"}],"Metascore":"64","imdbRating":"7.0","imdbVotes":"306,298","imdbID":"tt0910936","Type":"movie","DVD":"25 Mar 2008","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Step Brothers","Year":"2008","Rated":"R","Released":"25 Jul 2008","Runtime":"98 min","Genre":"Comedy","Director":"Adam McKay","Writer":"Will Ferrell (screenplay), Adam McKay (screenplay), Will Ferrell (story), Adam McKay (story), John C. Reilly (story)","Actors":"Will Ferrell, John C. Reilly, Mary Steenburgen, Richard Jenkins","Plot":"Two aimless middle-aged losers still living at home are forced against their will to become roommates when their parents marry.","Language":"English, Spanish","Country":"USA","Awards":"3 wins & 2 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BODViZDg3ZjYtMzhiYS00YTVkLTk4MzktYWUxMTlkYjc1NjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.9/10"},{"Source":"Rotten Tomatoes","Value":"55%"},{"Source":"Metacritic","Value":"51/100"}],"Metascore":"51","imdbRating":"6.9","imdbVotes":"257,559","imdbID":"tt0838283","Type":"movie","DVD":"02 Dec 2008","BoxOffice":"$100,468,793","Production":"Columbia Pictures","Website":"N/A","Response":"True"},
  {"Title":"Zodiac","Year":"2007","Rated":"R","Released":"02 Mar 2007","Runtime":"157 min","Genre":"Crime, Drama, Mystery, Thriller","Director":"David Fincher","Writer":"James Vanderbilt (screenplay), Robert Graysmith (book)","Actors":"Jake Gyllenhaal, Mark Ruffalo, Anthony Edwards, Robert Downey Jr.","Plot":"In the late 1960s/early 1970s, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer, an unidentified individual who terrorizes Northern California with a killing spree.","Language":"English","Country":"USA","Awards":"3 wins & 71 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BN2UwNDc5NmEtNjVjZS00OTI5LWE5YjctMWM3ZjBiZGYwMGI2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"89%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"7.7","imdbVotes":"429,555","imdbID":"tt0443706","Type":"movie","DVD":"24 Jul 2007","BoxOffice":"$33,000,000","Production":"Paramount Pictures","Website":"N/A","Response":"True"},
  {"Title":"The Blind Side","Year":"2009","Rated":"PG-13","Released":"20 Nov 2009","Runtime":"129 min","Genre":"Biography, Drama, Sport","Director":"John Lee Hancock","Writer":"John Lee Hancock, Michael Lewis (book)","Actors":"Sandra Bullock, Tim McGraw, Quinton Aaron, Jae Head","Plot":"The story of Michael Oher, a homeless and traumatized boy who became an All-American football player and first-round NFL draft pick with the help of a caring woman and her family.","Language":"English","Country":"USA","Awards":"Won 1 Oscar. Another 10 wins & 30 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjEzOTE3ODM3OF5BMl5BanBnXkFtZTcwMzYyODI4Mg@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.6/10"},{"Source":"Rotten Tomatoes","Value":"66%"},{"Source":"Metacritic","Value":"53/100"}],"Metascore":"53","imdbRating":"7.6","imdbVotes":"280,606","imdbID":"tt0878804","Type":"movie","DVD":"23 Mar 2010","BoxOffice":"$255,900,000","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
  {"Title":"Man on Fire","Year":"2004","Rated":"R","Released":"23 Apr 2004","Runtime":"146 min","Genre":"Action, Crime, Drama, Thriller","Director":"Tony Scott","Writer":"A.J. Quinnell (novel), Brian Helgeland (screenplay)","Actors":"Denzel Washington, Dakota Fanning, Radha Mitchell, Christopher Walken","Plot":"In Mexico City, a former CIA operative swears vengeance on those who committed an unspeakable act against the family he was hired to protect.","Language":"English, Spanish","Country":"USA, UK, Mexico, Switzerland","Awards":"1 win & 7 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BODFlMmEwMDgtYjhmZi00ZTE5LTk2NWQtMWE1Y2M0NjkzOGYxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"39%"},{"Source":"Metacritic","Value":"47/100"}],"Metascore":"47","imdbRating":"7.7","imdbVotes":"318,559","imdbID":"tt0328107","Type":"movie","DVD":"14 Sep 2004","BoxOffice":"$77,600,000","Production":"20th Century Fox","Website":"N/A","Response":"True"},
  {"Title":"Into the Wild","Year":"2007","Rated":"R","Released":"19 Oct 2007","Runtime":"148 min","Genre":"Adventure, Biography, Drama","Director":"Sean Penn","Writer":"Sean Penn (screenplay), Jon Krakauer (book)","Actors":"Emile Hirsch, Marcia Gay Harden, William Hurt, Jena Malone","Plot":"After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity and hitchhikes to Alaska to live in the wilderness. Along the way, Christopher encounters a series of characters that shape his life.","Language":"English, Danish","Country":"USA","Awards":"Nominated for 2 Oscars. Another 23 wins & 104 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTAwNDEyODU1MjheQTJeQWpwZ15BbWU2MDc3NDQwNw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"83%"},{"Source":"Metacritic","Value":"73/100"}],"Metascore":"73","imdbRating":"8.1","imdbVotes":"548,511","imdbID":"tt0758758","Type":"movie","DVD":"04 Mar 2008","BoxOffice":"$18,173,360","Production":"Paramount Vantage","Website":"N/A","Response":"True"}


























]